### ISSUE TITLE
update to 2.4.0

### ISSUE THREAD

**Issue by CamelT0E** [nagimov/agendav-docker#4]
please update to the last version

thx

**Comment by qduff** [comment]
A bit late here, but changing https://github.com/nagimov/agendav-docker/blob/master/Dockerfile#L5 to `ENV AGENDAV_VERSION 2.4.0` seems to work perfectly. It would however still be nice if @nagimov could upload newer images to the docker hub, given that 2.2.0 has some pretty bad timezone bugs - if you wouldn't mind.

**Comment by nagimov** [comment]
@qduff @nillebor yes, [`2.2.0-bullseye`](https://github.com/nagimov/agendav-docker/commit/d938b77607f6978375f311e2650d8109c2168b63) recipe works fine with latest `2.4.0` version.

Re. publishing 2.4.0 on docker-hub:

- docker-hub no longer offers continuous builds for free
- sharing container images on docker-hub now involves uploading binary blobs
- running unverified images from docker-hub is a bad practice, since it's difficult to verify that the uploaded image is built from these sources without the use of CI builds (might as well build it yourself)

I'm planning to publish these docker images on ghcr, but I haven't looked at the workflow yet. If anyone wants to help, I'm happy to share the repo access!

**Comment by nagimov** [comment]
@qduff @nillebor Dockerfile updated to 2.4.0, new image pushed to ghcr. Pull via `docker pull ghcr.io/nagimov/agendav-docker:2.4.0`
